FROM registry.redhat.io/ubi8/openjdk-17@sha256:af305e087061cbaa4107ce0b304a1ef987f6b54bae3f75bfd529cfd084cba9b5

USER root

RUN microdnf install -y unzip

WORKDIR /usr/share/maven

RUN rm -rf /usr/share/maven/* /usr/bin/mvn

RUN curl -L -o apache-maven-3.9.4-bin.zip https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip && \
    unzip apache-maven-3.9.4-bin.zip "apache-maven-3.9.4/*" -d "/usr/share/maven" && \
    ln -s /usr/share/maven/apache-maven-3.9.4/bin/mvn /usr/bin/mvn && \
    rm -rf apache-maven-3.9.4-bin.zip

ENV MAVEN_VERSION=3.9.4
ENV MAVEN_OPTS="-Xmx3489m"
ENV JAVA_TOOL_OPTION="-Xmx3489m"
ENV M2_HOME=/usr/share/maven/apache-maven-3.9.4/bin
ENV PATH=$PATH:/usr/share/maven/apache-maven-3.9.4/bin

RUN chown 1001:0 ${M2_HOME} && chgrp -R 0 ${M2_HOME} && chmod -R g=u ${M2_HOME}

RUN microdnf install -y dnf && \
    dnf -y module install nodejs:20 && \
    npm install -y -g yarn && \
    dnf -y install git

RUN npm install -y -g generator-jhipster@9.0.0

USER 1001
