apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.app.name }}'
  labels:
    app.kubernetes.io/managed-by: jhipster-online
    app.kubernetes.io/instance: '{{ .Values.app.name }}'
    app.kubernetes.io/part-of: '{{ .Values.app.name }}'
    app.kubernetes.io/name: '{{ .Values.app.name }}'
    app.openshift.io/runtime: java
  annotations:
    app.openshift.io/vcs-uri: '{{ .Values.git.repoUrl }}'
    deploy.jhipster.online/method: '{{ .Values.deploy.method }}'
spec:
  replicas: {{ .Values.replicas.app }}
  selector:
    matchLabels:
      app: '{{ .Values.app.name }}'
      deployment: '{{ .Values.app.name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.app.name }}'
        app.kubernetes.io/managed-by: jhipster-online
        app.kubernetes.io/instance: '{{ .Values.app.name }}'
        app.kubernetes.io/part-of: '{{ .Values.app.name }}'
        deployment: '{{ .Values.app.name }}'
        app.openshift.io/runtime: java
    spec:
{{- if .Values.rbac.create }}
      serviceAccountName: '{{ .Values.app.name }}-deployer'
{{- end }}
      containers:
        - name: '{{ .Values.app.name }}'
          image: image-registry.openshift-image-registry.svc:5000/{{ .Values.image.namespace }}/{{ .Values.image.stream }}:latest
          imagePullPolicy: Always
          env:
            - name: QUARKUS_PROFILE
              value: prod,api-docs
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mariadb://mariadb-{{ .Values.app.name }}:3306/jhipsteronline
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-{{ .Values.app.name }}
                  key: database-user
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-{{ .Values.app.name }}
                  key: database-password
            {{- if .Values.integrations.kafka.enabled }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: '{{ .Values.app.name }}-kafka-kafka-bootstrap:9092'
            {{- end }}
            {{- if .Values.integrations.redis.enabled }}
            - name: QUARKUS_REDIS_HOSTS
              value: 'redis://{{ .Values.app.name }}-redis:6379'
            {{- end }}
            {{- if and .Values.integrations.keycloak.enabled (ne .Values.integrations.keycloak.issuerUri "") }}
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: '{{ .Values.integrations.keycloak.issuerUri }}'
            {{- end }}
            - name: QUARKUS_HTTP_CORS
              value: 'true'
