apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-{{ .Values.app.name }}-data
  labels:
    app.kubernetes.io/managed-by: jhipster-online
    app.kubernetes.io/instance: '{{ .Values.app.name }}'
    app.kubernetes.io/part-of: '{{ .Values.app.name }}'
    app.kubernetes.io/name: mariadb-{{ .Values.app.name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
