{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.app.name }}-deployer'
  labels:
    app.kubernetes.io/managed-by: jhipster-online
    app.kubernetes.io/instance: '{{ .Values.app.name }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ .Values.app.name }}-deployer'
  labels:
    app.kubernetes.io/managed-by: jhipster-online
rules:
  - apiGroups: ['']
    resources: ['services', 'secrets', 'persistentvolumeclaims', 'configmaps']
    verbs: ['get', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['apps.openshift.io']
    resources: ['deploymentconfigs']
    verbs: ['get', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['route.openshift.io']
    resources: ['routes']
    verbs: ['get', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['image.openshift.io']
    resources: ['imagestreams', 'imagestreamtags']
    verbs: ['get', 'list', 'create', 'update', 'patch']
  - apiGroups: ['build.openshift.io']
    resources: ['buildconfigs', 'builds']
    verbs: ['get', 'list', 'create', 'update', 'patch']
  - apiGroups: ['build.openshift.io']
    resources: ['buildconfigs/instantiate', 'builds/log']
    verbs: ['create', 'get']
  - apiGroups: ['tekton.dev']
    resources: ['pipelines', 'tasks', 'pipelineruns', 'taskruns']
    verbs: ['get', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['tekton.dev']
    resources: ['pipelineruns/status', 'taskruns/status']
    verbs: ['get']
  - apiGroups: ['triggers.tekton.dev']
    resources: ['eventlisteners', 'triggerbindings', 'triggertemplates', 'triggers']
    verbs: ['get', 'list', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['argoproj.io']
    resources: ['applications']
    verbs: ['get', 'list', 'create', 'update', 'delete']
  - apiGroups: ['apps']
    resources: ['replicasets']
    verbs: ['get', 'list']
  - apiGroups: ['']
    resources: ['pods', 'pods/log', 'events']
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Values.app.name }}-deployer-binding'
  labels:
    app.kubernetes.io/managed-by: jhipster-online
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.app.name }}-deployer'
roleRef:
  kind: Role
  name: '{{ .Values.app.name }}-deployer'
  apiGroup: rbac.authorization.k8s.io
{{- end }}
