apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{ .Values.app.name }}
  labels:
    app.kubernetes.io/managed-by: jhipster-online
    app.kubernetes.io/instance: '{{ .Values.app.name }}'
    app.kubernetes.io/name: mariadb-{{ .Values.app.name }}
    app.openshift.io/runtime: mariadb
  annotations:
    template.openshift.io/expose-database_name: "{.data['database-name']}"
    template.openshift.io/expose-password: "{.data['database-password']}"
    template.openshift.io/expose-root_password: "{.data['database-root-password']}"
    template.openshift.io/expose-username: "{.data['database-user']}"
data:
  database-name: amhpcHN0ZXJvbmxpbmU=
  database-password: amhpcHN0ZXI=
  database-root-password: amhpcHN0ZXI=
  database-user: amhpcHN0ZXI=
type: Opaque
