apiVersion: v1
kind: Service
metadata:
  name: mariadb-{{ .Values.app.name }}
  labels:
    app.kubernetes.io/managed-by: jhipster-online
    app.kubernetes.io/instance: '{{ .Values.app.name }}'
    app.kubernetes.io/name: mariadb-{{ .Values.app.name }}
spec:
  ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb-{{ .Values.app.name }}
    deployment: mariadb-{{ .Values.app.name }}
