/**
 * MCP worker: copies stack templates, applies token replacement, optional extraFiles from AI editor; returns tar.gz or JSON preview.
 */
const express = require('express');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const PORT = Number(process.env.PORT || 8083);
/** Templates copied at image build from src/main/resources/mcp-server-template */
const TEMPLATE_ROOT = process.env.MCP_TEMPLATE_ROOT || path.join(__dirname, 'templates');

function logLine(msg) {
  // eslint-disable-next-line no-console
  console.log(`[mcp-worker ${new Date().toISOString()}] ${msg}`);
}

function sanitizeId(name) {
  let s = String(name).replace(/[^a-zA-Z0-9\-]/g, '-').toLowerCase();
  s = s.replace(/-+/g, '-');
  return s || 'mcp-server';
}

function text(obj, field, def) {
  const v = obj[field];
  if (typeof v !== 'string' || !v.trim()) {
    return def;
  }
  return v.trim();
}

function portFor(fw) {
  if (fw === 'dotnet') {
    return '5000';
  }
  if (fw === 'python') {
    return '8000';
  }
  return '8080';
}

function runCommandFor(fw) {
  if (fw === 'quarkus') {
    return './mvnw quarkus:dev';
  }
  if (fw === 'dotnet') {
    return 'dotnet run';
  }
  if (fw === 'python') {
    return 'pip install -e . && python server.py';
  }
  return './mvnw spring-boot:run';
}

function pythonToolFunctionName(toolName) {
  let s = String(toolName).replace(/[^a-zA-Z0-9_]/g, '_');
  if (!s) {
    return 'hello_tool';
  }
  if (!/^[a-zA-Z_]/.test(s)) {
    return 'tool_' + s;
  }
  return s;
}

function buildTokens(cfg) {
  const framework = text(cfg, 'mcpFramework', 'spring').toLowerCase();
  const projectName = sanitizeId(text(cfg, 'projectName', 'mcp-server'));
  const pkgDefault = 'com.example.' + projectName.replace(/-/g, '');
  const packageName = text(cfg, 'packageName', pkgDefault);
  const toolName = text(cfg, 'toolName', 'helloTool');
  const toolDescription = text(cfg, 'toolDescription', 'Example MCP tool generated by JHipster Online.');
  const pkgPath = packageName.replace(/\./g, '/');

  const tokens = {
    __PROJECT_NAME__: projectName,
    __PACKAGE_NAME__: packageName,
    __MCP_FRAMEWORK__: framework,
    __MCP_TOOL_NAME__: toolName,
    __MCP_TOOL_DESCRIPTION__: toolDescription,
    __MCP_PORT__: portFor(framework),
    __FRAMEWORK_RUN_COMMAND__: runCommandFor(framework),
    __ROOT_NAMESPACE__: projectName.replace(/-/g, '_'),
    __PYTHON_TOOL_FUNC__: pythonToolFunctionName(toolName)
  };
  return { framework, projectName, packageName, pkgPath, tokens };
}

function applyTokens(content, tokens) {
  let out = content;
  for (const [k, v] of Object.entries(tokens)) {
    out = out.split(k).join(v);
  }
  return out;
}

function templateDir(framework) {
  const fw = framework === 'quarkus' || framework === 'dotnet' || framework === 'python' ? framework : 'spring';
  return path.join(TEMPLATE_ROOT, fw);
}

function entriesFor(framework, pkgPath, projectName) {
  if (framework === 'quarkus') {
    return [
      ['pom.xml', 'pom.xml'],
      ['README.md', 'README.md'],
      ['src/main/resources/application.properties', 'src/main/resources/application.properties'],
      ['src/main/java/Application.java.tpl', `src/main/java/${pkgPath}/McpServerApplication.java`]
    ];
  }
  if (framework === 'dotnet') {
    return [
      ['Program.cs.tpl', 'Program.cs'],
      ['Project.csproj.tpl', `${projectName}.csproj`],
      ['README.md', 'README.md']
    ];
  }
  if (framework === 'python') {
    return [
      ['pyproject.toml', 'pyproject.toml'],
      ['server.py', 'server.py'],
      ['README.md', 'README.md']
    ];
  }
  return [
    ['pom.xml', 'pom.xml'],
    ['README.md', 'README.md'],
    ['src/main/resources/application.yml', 'src/main/resources/application.yml'],
    ['src/main/java/Application.java.tpl', `src/main/java/${pkgPath}/McpServerApplication.java`]
  ];
}

function skillPairs() {
  return [
    ['common/.cursor/skills/mcp-server-get-started/SKILL.md.tpl', '.cursor/skills/mcp-server-get-started/SKILL.md'],
    ['common/.cursor/skills/mcp-server-tools/SKILL.md.tpl', '.cursor/skills/mcp-server-tools/SKILL.md'],
    ['common/.cursor/skills/mcp-server-setup/SKILL.md.tpl', '.cursor/skills/mcp-server-setup/SKILL.md']
  ];
}

function copyTemplateToDir(workDir, cfg) {
  const { framework, projectName, pkgPath, tokens } = buildTokens(cfg);
  const base = templateDir(framework);

  for (const [srcRel, destRel] of entriesFor(framework, pkgPath, projectName)) {
    const srcPath = path.join(base, srcRel);
    const destPath = path.join(workDir, destRel);
    if (!fs.existsSync(srcPath)) {
      throw new Error('Missing template file: ' + srcPath);
    }
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    let content = fs.readFileSync(srcPath, 'utf8');
    fs.writeFileSync(destPath, applyTokens(content, tokens), 'utf8');
  }

  for (const [srcRel, destRel] of skillPairs()) {
    const srcPath = path.join(TEMPLATE_ROOT, srcRel);
    const destPath = path.join(workDir, destRel);
    if (!fs.existsSync(srcPath)) {
      throw new Error('Missing skill template: ' + srcPath);
    }
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    let content = fs.readFileSync(srcPath, 'utf8');
    fs.writeFileSync(destPath, applyTokens(content, tokens), 'utf8');
  }

  const cfgStr = typeof cfg === 'string' ? cfg : JSON.stringify(cfg, null, 2);
  fs.writeFileSync(path.join(workDir, 'mcp-server-config.json'), cfgStr, 'utf8');

  const extra = cfg.extraFiles;
  if (Array.isArray(extra)) {
    for (const f of extra) {
      if (f && f.path && typeof f.content === 'string') {
        let safe = String(f.path).replace(/\\/g, '/');
        safe = safe.replace(/^(\.\.\/)+/, '');
        if (safe.startsWith('/')) {
          safe = safe.substring(1);
        }
        const destPath = path.join(workDir, safe);
        fs.mkdirSync(path.dirname(destPath), { recursive: true });
        fs.writeFileSync(destPath, applyTokens(f.content, tokens), 'utf8');
      }
    }
  }
}

function collectFiles(workDir) {
  const out = {};
  const walk = d => {
    for (const ent of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, ent.name);
      const rel = path.relative(workDir, p).replace(/\\/g, '/');
      if (ent.isDirectory()) {
        walk(p);
      } else {
        out[rel] = fs.readFileSync(p, 'utf8');
      }
    }
  };
  walk(workDir);
  return out;
}

const app = express();
app.use(express.json({ limit: '16mb' }));

app.get('/health', (_req, res) => {
  res.status(200).type('text/plain').send('ok');
});

app.post('/preview', (req, res) => {
  let workDir;
  try {
    const cfg = req.body;
    if (!cfg || typeof cfg !== 'object') {
      return res.status(400).type('text/plain').send('Expected JSON object body');
    }
    workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mcpw-preview-'));
    copyTemplateToDir(workDir, cfg);
    res.status(200).json({ files: collectFiles(workDir) });
  } catch (e) {
    logLine('ERROR preview: ' + (e.message || String(e)));
    res.status(500).type('text/plain').send(e.message || String(e));
  } finally {
    if (workDir && fs.existsSync(workDir)) {
      try {
        fs.rmSync(workDir, { recursive: true, force: true });
      } catch (_) {
        /* ignore */
      }
    }
  }
});

app.post('/generate', (req, res) => {
  let workDir;
  const t0 = Date.now();
  try {
    const cfg = req.body;
    if (!cfg || typeof cfg !== 'object') {
      return res.status(400).type('text/plain').send('Expected JSON object body');
    }
    workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mcpw-'));
    copyTemplateToDir(workDir, cfg);
    const tarball = execFileSync('tar', ['-czf', '-', '-C', workDir, '.'], {
      encoding: 'buffer',
      maxBuffer: 256 * 1024 * 1024
    });
    res.status(200).type('application/gzip').send(tarball);
    logLine('tar sent in ' + (Date.now() - t0) + 'ms');
  } catch (e) {
    logLine('ERROR generate: ' + (e.message || String(e)));
    res.status(500).type('text/plain').send(e.message || String(e));
  } finally {
    if (workDir && fs.existsSync(workDir)) {
      try {
        fs.rmSync(workDir, { recursive: true, force: true });
      } catch (_) {
        /* ignore */
      }
    }
  }
});

app.listen(PORT, '0.0.0.0', () => {
  // eslint-disable-next-line no-console
  console.log('mcp-worker listening on ' + PORT + ' templates=' + TEMPLATE_ROOT);
});
