import { Component, OnInit } from '@angular/core';

import { JhiAlertService } from 'app/shared/alert/alert.service';
import { JdlAiModelOption } from 'app/home/jdl-metadata/jdl-ai.service';

import { McpExtraFile, McpGeneratorService } from './mcp-generator.service';

@Component({
  standalone: false,
  selector: 'jhi-mcp-generator',
  templateUrl: './mcp-generator.component.html'
})
export class McpGeneratorComponent implements OnInit {
  framework: 'spring' | 'quarkus' | 'dotnet' | 'python' = 'spring';
  projectName = 'mcp-demo';
  packageName = 'com.example.mcpdemo';
  toolName = 'helloTool';
  toolDescription = 'Example MCP tool generated by JHipster Online.';

  /** Optional AI-generated file merged by mcp-worker */
  extraFilePath = '';
  extraFileContent = '';

  jdlPaste = '';
  jdlToolsOutput = '';
  expandPrompt = '';
  expandOutput = '';

  previewFiles: Record<string, string> = {};
  previewKeys: string[] = [];
  activePreviewKey = '';

  assistantEnabled = false;
  models: JdlAiModelOption[] = [];
  selectedModelId = '';

  loadingPreview = false;
  loadingDownload = false;
  loadingJdlTools = false;
  loadingExpand = false;

  constructor(private mcpGeneratorService: McpGeneratorService, private alertService: JhiAlertService) {}

  ngOnInit(): void {
    this.mcpGeneratorService.getMcpAiConfig().subscribe({
      next: c => {
        this.assistantEnabled = c.enabled;
        this.models = c.models ?? [];
        this.selectedModelId = (c.defaultModelId ?? this.models[0]?.id ?? '').trim();
      },
      error: () => {
        this.assistantEnabled = false;
      }
    });
  }

  buildConfig(): Record<string, unknown> {
    const extra: McpExtraFile[] = [];
    if (this.extraFilePath.trim().length > 0 && this.extraFileContent.trim().length > 0) {
      extra.push({ path: this.extraFilePath.trim(), content: this.extraFileContent });
    }
    const cfg: Record<string, unknown> = {
      generatorType: 'mcp-server',
      mcpFramework: this.framework,
      projectName: this.projectName.trim(),
      packageName: this.packageName.trim(),
      toolName: this.toolName.trim(),
      toolDescription: this.toolDescription.trim()
    };
    if (extra.length > 0) {
      cfg.extraFiles = extra;
    }
    return cfg;
  }

  refreshPreview(): void {
    this.loadingPreview = true;
    this.mcpGeneratorService.preview(this.buildConfig()).subscribe({
      next: res => {
        this.previewFiles = res.files ?? {};
        this.previewKeys = Object.keys(this.previewFiles).sort();
        this.activePreviewKey = this.previewKeys[0] ?? '';
        this.loadingPreview = false;
      },
      error: err => {
        this.loadingPreview = false;
        const body = err.error;
        const msg =
          typeof body === 'object' && body && body.detail ? body.detail : err.message ?? 'Preview failed (is mcp-worker enabled?)';
        this.alertService.addAlert({ type: 'danger', msg: String(msg) });
      }
    });
  }

  selectPreviewKey(key: string): void {
    this.activePreviewKey = key;
  }

  activePreviewContent(): string {
    return this.activePreviewKey ? this.previewFiles[this.activePreviewKey] ?? '' : '';
  }

  downloadZip(): void {
    this.loadingDownload = true;
    this.mcpGeneratorService.downloadZip(this.buildConfig()).subscribe({
      next: resp => {
        this.loadingDownload = false;
        const blob = resp.body;
        if (blob) {
          this.downloadBlob(blob, `${this.projectName.trim() || 'mcp-server'}.zip`);
        }
      },
      error: () => {
        this.loadingDownload = false;
        this.alertService.addAlert({ type: 'danger', msg: 'Download failed (check MCP worker and logs).' });
      }
    });
  }

  generateToolsFromJdl(): void {
    if (!this.assistantEnabled) {
      this.alertService.addAlert({ type: 'warning', msg: 'AI is not configured on this server.' });
      return;
    }
    this.loadingJdlTools = true;
    this.mcpGeneratorService
      .jdlToTools({
        jdl: this.jdlPaste,
        framework: this.framework,
        modelId: this.selectedModelId || undefined
      })
      .subscribe({
        next: r => {
          this.jdlToolsOutput = r.text ?? '';
          this.loadingJdlTools = false;
        },
        error: () => {
          this.loadingJdlTools = false;
          this.alertService.addAlert({ type: 'danger', msg: 'JDL → MCP tools request failed.' });
        }
      });
  }

  applyJdlToolsToExtraFile(): void {
    this.extraFileContent = this.jdlToolsOutput;
    if (!this.extraFilePath.trim()) {
      this.extraFilePath = this.defaultExtraPath();
    }
    this.alertService.addAlert({ type: 'success', msg: 'AI output copied to extra file fields. Adjust path if needed, then Preview.' });
  }

  expandWithAi(): void {
    if (!this.assistantEnabled) {
      this.alertService.addAlert({ type: 'warning', msg: 'AI is not configured on this server.' });
      return;
    }
    this.loadingExpand = true;
    const baseJson = JSON.stringify(this.buildConfig(), null, 2);
    this.mcpGeneratorService
      .expand({
        framework: this.framework,
        baseMcpConfigJson: baseJson,
        jdlContext: this.jdlPaste,
        userPrompt: this.expandPrompt,
        modelId: this.selectedModelId || undefined
      })
      .subscribe({
        next: r => {
          this.expandOutput = r.text ?? '';
          this.loadingExpand = false;
        },
        error: () => {
          this.loadingExpand = false;
          this.alertService.addAlert({ type: 'danger', msg: 'AI expansion failed.' });
        }
      });
  }

  private defaultExtraPath(): string {
    if (this.framework === 'dotnet') {
      return 'Tools/GeneratedEntityTools.cs';
    }
    if (this.framework === 'python') {
      return 'src/generated_entity_tools.py';
    }
    const pkg = this.packageName.replace(/\./g, '/');
    return `src/main/java/${pkg}/tools/EntityTools.java`;
  }

  private downloadBlob(blob: Blob, filename: string): void {
    const a = document.createElement('a');
    const fileURL = URL.createObjectURL(blob);
    a.href = fileURL;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(fileURL);
  }
}
