apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __APP_NAME__
  namespace: __ARGOCD_APP_NAMESPACE__
  labels:
    app.kubernetes.io/managed-by: jhipster-online
    app.kubernetes.io/instance: __APP_NAME__
spec:
  project: default
  source:
    repoURL: __GIT_REPO_URL__
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: __TARGET_NAMESPACE__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
